mots = [
    "pain", "pomme", "chat", "maison", "plage", "soleil", "ordinateur", "musique", "livre", "fenetre",
    "voiture", "montagne", "fleur", "etoile", "cuisine", "aventure", "bonheur", "ecole", "amour", "amitie",
    "table", "chaise", "ciel", "nuage", "jour", "nuit", "etoile", "terre", "mer", "ocean",
    "poisson", "oiseau", "chaton", "chiot", "famille", "ami", "jardin", "foret", "riviere", "cascade",
    "energie", "bonjour", "bonsoir", "aurevoir", "merci", "sourire", "rire", "pleurer", "espoir", "reve",
    "belle", "elegant", "heureux", "triste", "fier", "libre", "fort", "doux", "delicat", "calme",
    "orage", "tempete", "eclair", "eclat", "parfum", "saveur", "couleur", "rouge", "bleu", "vert",
    "jaune", "orange", "violet", "noir", "blanc", "gris", "rose", "lune", "etoile", "planete",
    "explorer", "decouvrir", "voyage", "aventure", "nouveau", "ancien", "moderne", "passe", "avenir", "sante",
    "esprit", "corps", "ame", "pensee", "idee", "creation", "art", "musee", "exposition", "peinture",
    "sculpture", "cinema", "theatre", "danse", "poesie", "ecrire", "lire", "livre", "histoire", "roman",
    "science", "mathematiques", "physique", "chimie", "biologie", "astronomie", "espace", "temps", "passe", "present",
    "futur", "journee", "semaine", "mois", "annee", "decennie", "siecle", "milleenaire", "evolution", "revolution",
    "technologie", "informatique", "internet", "reseau", "programme", "algorithme", "robot", "intelligence", "artificielle", "machine",
    "travail", "emploi", "carriere", "succes", "echec", "apprentissage", "education", "ecole", "universite", "professeur",
    "etudiant", "connaissance", "savoir", "comprendre", "penser", "raisonner", "question", "reponse", "probleme", "solution",
    "creativite", "innovation", "invention", "developpement", "progression", "changement", "amelioration", "societe", "communaute", "citoyen",
    "politique", "gouvernement", "democratie", "liberte", "egalite", "fraternite", "justice", "paix", "guerre", "conflit",
    "amour", "haine", "relation", "communication", "conversation", "ecoute", "parole", "expression", "emotion", "sentiment",
    "joie", "peur", "colere", "tristesse", "espoir", "reve", "inspiration", "motivation", "objectif", "realisation",
    "sport", "musique", "danse", "art", "nature", "environnement", "ecologie", "climat", "energie", "ressource",
    "alimentation", "sante", "bienetre", "mode", "beaute", "style", "tendance", "voyage", "aventure", "exploration",
    "decouverte", "divertissement", "jeu", "humour", "rire", "plaisir", "fete", "celebration", "tradition", "coutume",
    "religion", "spiritualite", "foi", "croyance", "rituel", "pratique", "meditation", "paix", "harmonie", "tolerance",
    "diversite", "inclusion", "respect", "ethique", "valeurs", "morale", "integrite", "responsabilite", "engagement", "solidarite",
    "generosite", "altruisme", "benevolat", "charite", "entraide", "cooperation", "collaboration", "equipe", "leadership", "management",
    "entreprise", "innovation", "creativite", "entrepreneuriat", "startup", "succes", "echec", "apprentissage", "risque", "opportunite",
    "finance", "economie", "marche", "investissement", "croissance", "developpement", "globalisation", "commerce", "industrie", "technologie",
    "numerique", "internet", "reseaux sociaux", "communication", "information", "donnees", "securite", "vieprivee", "ethique", "intelligenceartificielle",
    "machinelearning", "apprentissageautomatique", "realitevirtuelle", "blockchain", "cryptomonnaie", "bitcoin", "cryptographie", "securiteinformatique", "cybersecurite",
    "robots", "automatisation", "travail", "emploi", "formation", "competences", "education", "apprentissage", "enseignement", "pedagogie", "didactique",
    "environnement", "ecologie", "climat", "energiesrenouvelables", "developpementdurable", "conservation", "biodiversite", "ecotourisme", "responsabilite", "recyclage",
    "alimentation", "nutrition", "sante", "bienetre", "maladie", "medecine", "recherche", "innovation", "pharmacie", "biotechnologie",
    "espace", "astronomie", "explorationspatiale", "planetes", "etoiles", "galaxies", "cosmos", "theories", "univers", "temps",
    "histoire", "archeologie", "civilisation", "prehistoire"
]